--- #YAML:1.0
name: Catalyst-Plugin-Session-Store-CDBI
version: 0.02
author:
  - Jason Woodward E<lt>C<woodwardj@jaos.org>E<gt>
  - Based on work by
Lyo Kato E<lt>lyo.kato@gmail.comE<gt>
Yuval Kogman E<lt>C<nothingmuch@woobling.org>E<gt>
Sebastian Riedel E<lt>C<sri@cpan.org>E<gt>,
Marcus Ramberg E<lt>C<mramberg@cpan.org>E<gt>,
Andrew Ford E<lt>C<andrewf@cpan.org>E<gt>,
abstract: CDBI sessions for Catalyst
license: perl
generated_by: Module::Build version 0.2611, without YAML.pm
